### ISSUE TITLE
Will it work with other couchbase versions like 4.6.5 ?

### ISSUE THREAD

**Issue by amithrh** [blakelead/couchbase_exporter#21]
@blakelead , i need to use it on VMs , do i have to make any change to use this ?

**Comment by blakelead** [comment]
Hi @amithrh,

I haven't tested it on this particular version but it will work.

You will see a warning in the log though, stating that version 4.6.5 is not supported. I will test the exporter against the version you need and add this version to the supported ones.

**Comment by amithrh** [comment]
@blakelead Thanks a lot . I have some more question.
1. i want to install it on couchbase cluster running on VMs , do i need to make any change ?
2. Do it have installation dependency ?

**Comment by blakelead** [comment]
@amithrh you don't need to make any changes to your cluster and the exporter does not have any dependency, you just need to drop the binary on the VMs and execute it. 

I provided a [systemd](https://github.com/blakelead/couchbase_exporter/blob/master/examples/systemd-exporter.service) example if you need it, and you also can launch the exporter as a [Docker](https://hub.docker.com/r/blakelead/couchbase-exporter) container.

Tell me if you have any trouble using the exporter :)

**Comment by blakelead** [comment]
After some tests, it appears that the exporter works seamlessly with version 4.6.5.

FYI, comparing to version 4.5.1, version 4.6.5 is missing the following metrics:

```
cb_bucketstats_ep_tap_rebalance_count
cb_bucketstats_ep_tap_rebalance_qlen
cb_bucketstats_ep_tap_rebalance_queue_backfillremaining
cb_bucketstats_ep_tap_rebalance_queue_backoff
cb_bucketstats_ep_tap_rebalance_queue_drain
cb_bucketstats_ep_tap_rebalance_queue_fill
cb_bucketstats_ep_tap_rebalance_queue_itemondisk
cb_bucketstats_ep_tap_rebalance_total_backlog_size
cb_bucketstats_ep_tap_replica_count
cb_bucketstats_ep_tap_replica_qlen
cb_bucketstats_ep_tap_replica_queue_backfillremaining
cb_bucketstats_ep_tap_replica_queue_backoff
cb_bucketstats_ep_tap_replica_queue_drain
cb_bucketstats_ep_tap_replica_queue_fill
cb_bucketstats_ep_tap_replica_queue_itemondisk
cb_bucketstats_ep_tap_replica_total_backlog_size
cb_bucketstats_ep_tap_total_count
cb_bucketstats_ep_tap_total_qlen
cb_bucketstats_ep_tap_total_queue_backfillremaining
cb_bucketstats_ep_tap_total_queue_backoff
cb_bucketstats_ep_tap_total_queue_drain
cb_bucketstats_ep_tap_total_queue_fill
cb_bucketstats_ep_tap_total_queue_itemondisk
cb_bucketstats_ep_tap_total_total_backlog_size
cb_bucketstats_ep_tap_user_count
cb_bucketstats_ep_tap_user_qlen
cb_bucketstats_ep_tap_user_queue_backfillremaining
cb_bucketstats_ep_tap_user_queue_backoff
cb_bucketstats_ep_tap_user_queue_drain
cb_bucketstats_ep_tap_user_queue_fill
cb_bucketstats_ep_tap_user_queue_itemondisk
cb_bucketstats_ep_tap_user_total_backlog_size
```

I close this issue, but don't hesitate to open a new one if you have another question, or if you have trouble using the exporter :)
