### ISSUE TITLE
Support for Couchbase 6.x

### ISSUE THREAD

**Issue by PasqualePuzio** [blakelead/couchbase_exporter#24]
Hi,

is Couchbase 6.x supported?

I haven't tested it yet, thought you probably already know if it's the case or not.

Thanks

**Comment by blakelead** [comment]
Hello @PasqualePuzio,
Actually I did not test Couchbase 6. I'll do it this week and let you know :)

**Comment by aabdelhak** [comment]
Hi @PasqualePuzio,
I tested it and it works as expected with version 0.6.0 of the exporter. Could you confirm ?

**Comment by blakelead** [comment]
Hi @PasqualePuzio,
I tested it with version 0.6.0 of the exporter and it works as expected. Could you confirm ?

**Comment by PasqualePuzio** [comment]
Hi, thank you for confirming it works. I've tested it too and I had no issues. Seems to work fine with Couchbase 6.
