### ISSUE TITLE
Cluster configuration

### ISSUE THREAD

**Issue by ben-foster-cko** [blakelead/couchbase_exporter#29]
Is it necessary to run the exporter against each node in the cluster? Also what permissions are required by the exporter to get statistics?

**Comment by blakelead** [comment]
Hello @ben-foster-cko,

Yes you have to run one exporter per node.

As for permissions, you don't need particular privileges to run the exporter, but you must set credentials for the exporter to query the Couchbase API.

For versions of Couchbase before RBAC implementation you'd need global (admin) credentials and for versions with RBAC (>=5) you can create a special user for the exporter with read permissions.

Thanks for using the exporter and don't hesitate if you have any more question.
