### ISSUE TITLE
Memcached moxi exporter

### ISSUE THREAD

**Issue by williamhammond** [blakelead/couchbase_exporter#30]
I'm guessing not but does this exporter capture any of the stats exposed by moxi `stats proxy` command described here https://developer.couchbase.com/documentation/server/3.x/admin/Monitoring/monitor-moxi-statistics.html?

**Comment by blakelead** [comment]
Hello @williamhammond,

Indeed I don't expose those metrics as I actually didn't know about them :). I'll read the docs and consider implementing it but I cannot assure you that this will be integrated to the exporter.

Anyway thanks for your interest in this project!

**Comment by blakelead** [comment]
@williamhammond , I'm closing this issue since I don't plan to implement this feature.
