### ISSUE TITLE
Support Couchbase 6.0

### ISSUE THREAD

**Issue by dream4r1** [blakelead/couchbase_exporter#31]
Saw similar question was raised before when we started the exporter we are having this warnings reported and we do not see the metrics are spitted out.
`
[root]# ./couchbase2_exporter -scrape.xdcr=false
INFO[0000] Couchbase version: 6.0.0-1693-community
INFO[0000] Community version: true
WARN[0000] Version 6.0.0-1693-community may not be supported by this exporter
INFO[0000] Listening at :9420
`

**Comment by blakelead** [comment]
Hey @dream4r1 , thanks for using the exporter!

Do you mean that you have no metrics at all ? Which version of the exporter do you use ? Are errors logs generated when scraping the exporter ?

**Comment by dash042** [comment]
bucket and xdcr do not seem to bring up metrics with the latest image from dockerhub: (latest)
`time="2019-05-13T13:45:14Z" level=debug msg="No value found for num_failedckpts metric in remote 7e0460e427013c6b30178f65ff9ea5bb"
`

**Comment by dream4r1** [comment]
Thanks @blakelead appreciate the response we figured its the internal curl issue rather being the exporter.

**Comment by blakelead** [comment]
Glad you resolved your issue :)
