### ISSUE TITLE
Support for Couchbase Sync-Gateway +2.5 metrics

### ISSUE THREAD

**Issue by khanium** [blakelead/couchbase_exporter#32]
Couchbase Sync Gateway was released on 29 April 2019 and contains support to metrics in the Sync Gateway servers. it would be great if couchbase_exporter could support it too.

**Comment by blakelead** [comment]
Hey @khanium , great suggestion!
I'll look into it as soon as I can.

**Comment by blakelead** [comment]
@khanium , I'm closing this issue since Couchbase is working on an official exporter for Sync-Gateway: https://github.com/couchbaselabs/couchbase-sync-gateway-exporter
