### ISSUE TITLE
Issue with docker image run

### ISSUE THREAD

**Issue by amithrh** [blakelead/couchbase_exporter#37]
i am trying to run docker image with all default value , but container is existing with below error:

docker run blakelead/couchbase-exporter:0.6.0
time="2019-06-19T11:09:45Z" level=info msg="stat /bin/config.yml: no such file or directory: using command-line parameters and/or environment variables if provided"
time="2019-06-19T11:09:45Z" level=info msg="Couchbase Exporter Version: 0.6.0"
time="2019-06-19T11:09:45Z" level=info msg="Supported Couchbase versions: 4.5.1, 4.6.5, 5.1.1"
time="2019-06-19T11:09:45Z" level=info msg="config.file=config.yml"
time="2019-06-19T11:09:45Z" level=info msg="web.listen-address=9191"
time="2019-06-19T11:09:45Z" level=info msg="web.telemetry-path=/metrics"
time="2019-06-19T11:09:45Z" level=info msg="web.timeout=0s"
time="2019-06-19T11:09:45Z" level=info msg="db.uri=http://127.0.0.1:8091"
time="2019-06-19T11:09:45Z" level=info msg="db.timeout=0s"
time="2019-06-19T11:09:45Z" level=info msg="log.level=info"
time="2019-06-19T11:09:45Z" level=info msg="log.format=text"
time="2019-06-19T11:09:45Z" level=info msg="scrape.cluster=true"
time="2019-06-19T11:09:45Z" level=info msg="scrape.node=true"
time="2019-06-19T11:09:45Z" level=info msg="scrape.bucket=true"
time="2019-06-19T11:09:45Z" level=info msg="scrape.xdcr=false"
time="2019-06-19T11:09:45Z" level=info msg="Started listening at 9191"
time="2019-06-19T11:09:45Z" level=fatal msg="listen tcp: address 9191: missing port in address"

Do you have the kubernets deployment file for this ?

**Comment by blakelead** [comment]
Hello @amithrh ,

Thank you for your valuable input!

There seem to be an issue with the default parameters indeed. I'll check that asap. In the mean time, you have two choices to bypass this bug:
- ~~use the tag 0.7.0~~ I also found the bug in this version
- explicitly pass environment variables or arguments to overwrite the faulty value:

```bash
docker run -e CB_EXPORTER_LISTEN_ADDR=:9191 blakelead/couchbase-exporter:0.6.0
```

Do not hesitate if you have more inputs/remarks

**Comment by blakelead** [comment]
Hello again @amithrh,

This is fixed in version 0.8.1. Could you please check ?

**Comment by amithrh** [comment]
Yeah it worked like charm

**Comment by blakelead** [comment]
Great! I close the issue then, thanks for your help.
