### ISSUE TITLE
couchbase_export build failed

### ISSUE THREAD

**Issue by zouzc** [blakelead/couchbase_exporter#42]
go build
# github.com/leansys-team/couchbase_exporter
./couchbase_exporter.go:62:3: unknown field 'TLSEnabled' in struct literal of type collector.Context
./couchbase_exporter.go:63:3: unknown field 'TLSSkipInsecure' in struct literal of type collector.Context
./couchbase_exporter.go:64:3: unknown field 'TLSCACert' in struct literal of type collector.Context
./couchbase_exporter.go:65:3: unknown field 'TLSClientCert' in struct literal of type collector.Context
./couchbase_exporter.go:66:3: unknown field 'TLSClientKey' in struct literal of type collector.Context

## go mod collector source is not new
diff collector/common.go /mnt/e/go/dev/pkg/mod/github.com/blakelead/couchbase_exporter@v0.0.0-20190619133003-7860afde272f/collector/common.go
9,10d8
<       "crypto/tls"
<       "crypto/x509"
40,52c38,45
<       URI             string
<       Username        string
<       Password        string
<       Timeout         time.Duration
<       ScrapeCluster   bool
<       ScrapeNode      bool
<       ScrapeBucket    bool
<       ScrapeXDCR      bool
<       TLSEnabled      bool
<       TLSSkipInsecure bool
<       TLSCACert       string
<       TLSClientCert   string
<       TLSClientKey    string
---
>       URI           string
>       Username      string
>       Password      string
>       Timeout       time.Duration
>       ScrapeCluster bool
>       ScrapeNode    bool
>       ScrapeBucket  bool
>       ScrapeXDCR    bool
121,128d113
<       tlsClientConfig := &tls.Config{}
<       if c.TLSEnabled {
<               tlsClientConfig, err = createTLSClientConfig(c)
<               if err != nil {
<                       log.Error(err)
<               }
<       }
<
130,136c115
<       client := http.Client{
<               Timeout: c.Timeout,
<               Transport: &http.Transport{
<                       TLSClientConfig: tlsClientConfig,
<               },
<       }
<
---
>       client := http.Client{Timeout: c.Timeout}
138d116
<
143d120
<
266,288d242
< }
<
< // createTLSClientConfig loads certificates and create TLS config
< func createTLSClientConfig(c Context) (*tls.Config, error) {
<       caCert, err := ioutil.ReadFile(c.TLSCACert)
<       if err != nil {
<               return nil, err
<       }
<       certPool := x509.NewCertPool()
<       certPool.AppendCertsFromPEM(caCert)
<
<       keyPair, err := tls.LoadX509KeyPair(c.TLSClientCert, c.TLSClientKey)
<       if err != nil {
<               return nil, err
<       }
<
<       config := tls.Config{
<               Certificates:       []tls.Certificate{keyPair},
<               ClientCAs:          certPool,
<               InsecureSkipVerify: c.TLSSkipInsecure,
<       }
<
<       return &config, nil

**Comment by blakelead** [comment]
Hello @zouzc 

Thanks for opening this issue, I'll try my best to help.

Could you give me more details, like which version of the exporter are you trying to build?
Also, it would be great if you'd better formulate your question because I have trouble understanding it, to be honest.

**Comment by zouzc** [comment]
go version
go version go1.12.9 linux/amd64

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

$git branch
* master
$ git log
commit 0ce90e11670984b9125b28432ace3bf1d035403d
Merge: 7860afd d6ebfb1
Author: blakelead <adel.abdelhak.lille@gmail.com>
Date:   Fri Aug 16 09:44:25 2019 +0200

    Merge branch 'release/0.9.0'

**Comment by blakelead** [comment]
Thanks, @zouzc  and sorry for the delay.

I reproduced the bug, and I fixed it in master branch. Could you test again, please?
