### ISSUE TITLE
multiple xdcr crashes the exporter

### ISSUE THREAD

**Issue by bennydubois** [blakelead/couchbase_exporter#43]
exporter version 0.9.0
couchbase version 5.0.1-5003 (community)

Issue: setting up a couchbase cluster to replicate to 2 datacenters (each with a distinct cluster id and name) throws the exporter in a strange loop. After a few prometheus scrape it uses over 1030 file descriptors and errors out with this for every xdcr metrics.

> * collected metric "cb_xdcr_error_count" { label:<name:"destination_bucket" value:"XXXXX" > label:<name:"remote_cluster_id" value:"YYYY" > label:<name:"remote_cluster_name" value:"backup" > label:<name:"source_bucket" value:"ZZZZ" > gauge:<value:0 > } was collected before with the same name and label values

**Comment by blakelead** [comment]
Hello @bennydubois,

Thank you for reporting this. I wanted to rework the XDCR part for some time, now I have to :)

I'll do my best to work on this issue next weekend.

**Comment by blakelead** [comment]
@bennydubois it is fixed in [0.9.5](https://github.com/blakelead/couchbase_exporter/releases/tag/0.9.5).

**Comment by bennydubois** [comment]
I rolled it out and it works perfectly, many thanks!
