### ISSUE TITLE
Difference between this and Couchbase Official Prometheus Exporter

### ISSUE THREAD

**Issue by Lumotheninja** [blakelead/couchbase_exporter#49]
Hello, I am just wondering what is the difference between this project and the official Couchbase exporter: https://github.com/couchbase/couchbase-exporter

**Comment by blakelead** [comment]
Hi @Lumotheninja,

I'd suppose that the official exporter is much more comprehensive in covering Couchbase features and metrics, but I can't give you a real answer as I haven't tested it.

If you have the opportunity to compare them, I would love to hear your opinion!

**Comment by Lumotheninja** [comment]
Well @blakelead , here is what I found out in general:

- Official Couchbase exporter (OCE) copied a lot of bucket stats into cbpernode bucket stats which makes it possible to filter by node and bucket, but you would need to run them on each server
- Most of the other stats are just moving names around, cb_cluster stats to cb_task stats
-  OCE has some interesting stats, literally called interesting stats, e.g. cbnode_interestingstats_cmd_get # HELP cbnode_interestingstats_cmd_get interestingstats_cmd_get. I have no idea what it does
- Other than the per node stats and the official Couchbase stamp (which may matter if you are an Enterprise customer), I don't find a big difference

**Comment by blakelead** [comment]
Thanks for your feedback @Lumotheninja !
