### ISSUE TITLE
The new version is not running

### ISSUE THREAD

**Issue by nexusguy59** [blakelead/couchbase_exporter#5]
Hey there,

I tried the new build and it exits immediately after creating:

I run it with: **docker run --name cbexporter -p 9191:9191 -e CB_EXPORTER_TELEMETRY_PATH=/metrics -e CB_EXPORTER_DB_URI=http://10.7.62.132 -e CB_EXPORTER_DB_USER=prometheus -e CB_EXPORTER_DB_PASSWORD=prompwd blakelead/couchbase-exporter:latest**

Then i see this: _**cdfb3009fb0f        blakelead/couchbase-exporter:latest   "/bin/sh -c /bin/cou…"   6 seconds ago       Exited (1) 5 seconds ago                                               cbexporter**_

Thanks for your input

**Comment by blakelead** [comment]
Hi Michael,

Thank you for your feedback, much appreciated!

I just tried with the following command : 
```
$ docker run --name cbexporter -p 9191:9191 -e CB_EXPORTER_TELEMETRY_PATH=/metrics -e CB_EXPORTER_DB_URI=http://cb-test.local:5091 -e CB_EXPORTER_DB_USER=*** -e CB_EXPORTER_DB_PASSWORD=*** blakelead/couchbase-exporter:latest
Unable to find image 'blakelead/couchbase-exporter:latest' locally
latest: Pulling from blakelead/couchbase-exporter
4fe2ade4980c: Pull complete
a7a8cc118f8f: Pull complete
Digest: sha256:c80c78d66d74069697a4d871c897a8542235c071403561f60fa24c1292ba1467
Status: Downloaded newer image for blakelead/couchbase-exporter:latest
time="2018-09-12T13:06:01Z" level=info msg="Couchbase version: 5.1.1-5723-community"
time="2018-09-12T13:06:01Z" level=info msg="Community version: true"
time="2018-09-12T13:06:01Z" level=info msg="Listening at :9191"
```
 and it works as expected for me.

You did not set a port in `CB_EXPORTER_DB_URI`, is this normal ?
Is this the only logs that you have ?

**Comment by nexusguy59** [comment]
Hello Adel,

In my terminal window I am seeing the following:

time="2018-09-12T14:20:45Z" level=error msg="json: cannot unmarshal number 2658.976930792377 into Go struct field .ops of type int"
time="2018-09-12T14:20:45Z" level=error msg="json: cannot unmarshal number 5214.976930792377 into Go struct field .opsPerSec of type int"
time="2018-09-12T14:20:50Z" level=error msg="json: cannot unmarshal number 2437.562437562437 into Go struct field .ops of type int"
time="2018-09-12T14:20:50Z" level=error msg="json: cannot unmarshal number 5178.303178303178 into Go struct field .opsPerSec of type int"

Is this something we need to be concerned about?

Thanks,
Michael

**Comment by blakelead** [comment]
I fixed this issue today, could you pull again the latest image and retry ?

**Comment by nexusguy59** [comment]
Hello, I will pull it in the morning and re run it and let ya know thanks

**Comment by blakelead** [comment]
Hi Michael, were you able to test the image ?

**Comment by nexusguy59** [comment]
Yes sir it is working,

**Comment by blakelead** [comment]
Glad to hear it, I'll close the issue then.

**Comment by nexusguy59** [comment]
I'm sorry I should have closed it my bad.

**Comment by blakelead** [comment]
No worries :)
